# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 779)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(18, 11, 891, 101))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 14))
        self.label.setObjectName("label")
        self.textEdit_filename = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_filename.setGeometry(QtCore.QRect(80, 20, 791, 41))
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.pushButton_readandcalculate = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_readandcalculate.setGeometry(QtCore.QRect(80, 70, 171, 21))
        self.pushButton_readandcalculate.setObjectName("pushButton_readandcalculate")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(18, 118, 891, 651))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 29, 141, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 30, 711, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_pumpname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_pumpname.setObjectName("lineEdit_pumpname")
        self.verticalLayout_2.addWidget(self.lineEdit_pumpname)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_flowunits = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_flowunits.setObjectName("lineEdit_flowunits")
        self.horizontalLayout.addWidget(self.lineEdit_flowunits)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_headunits = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_headunits.setObjectName("lineEdit_headunits")
        self.horizontalLayout.addWidget(self.lineEdit_headunits)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lineEdit_headcoeff = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_headcoeff.setObjectName("lineEdit_headcoeff")
        self.verticalLayout_2.addWidget(self.lineEdit_headcoeff)
        self.lineEdit_efficiencycoeff = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_efficiencycoeff.setObjectName("lineEdit_efficiencycoeff")
        self.verticalLayout_2.addWidget(self.lineEdit_efficiencycoeff)
        self.pushButton_exit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_exit.setGeometry(QtCore.QRect(800, 620, 81, 21))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Input"))
        self.label.setText(_translate("Dialog", "Filename"))
        self.pushButton_readandcalculate.setText(_translate("Dialog", "Read File and Calculate"))
        self.groupBox_2.setTitle(_translate("Dialog", "Output"))
        self.label_3.setText(_translate("Dialog", "Pump Name"))
        self.label_5.setText(_translate("Dialog", "Flow Units"))
        self.label_4.setText(_translate("Dialog", "Head Coefficients"))
        self.label_2.setText(_translate("Dialog", "Efficiency Coefficients"))
        self.label_6.setText(_translate("Dialog", "Head Units: "))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
